# Generated by Django 5.2 on 2025-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_generic',
            field=models.TextField(default='', help_text='Password generic', verbose_name='pass generic'),
        ),
    ]
