# Generated by Django 5.2 on 2025-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_pass_generic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_support',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_generic',
        ),
        migrations.AddField(
            model_name='user',
            name='file_info',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
